export const fakeApiResponse = {
  results: [
    {
      fsq_id: '1234-1',
      name: 'Test Place 1',
      categories: [
        {
          id: 1,
          name: 'Café',
          short_name: 'Cafe',
          plural_name: 'Cafés',
          icon: {
            id: 'icon123-1',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-1',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Great coffee',
              url: 'https://example.com/tip1',
              lang: 'en',
              agree_count: 10,
              disagree_count: 2,
            },
          },
        },
      ],
      location: {
        address: '123 Main St',
        formatted_address: '123 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.7128,
          longitude: -74.006,
        },
      },
      distance: 100,
      rating: 4.5,
      tel: '555-555-5551',
      website: 'https://testplace1.example.com',
    },
    {
      fsq_id: '1234-2',
      name: 'Test Place 2',
      categories: [
        {
          id: 2,
          name: 'Restaurant',
          short_name: 'Rest',
          plural_name: 'Restaurants',
          icon: {
            id: 'icon123-2',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-2',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Delicious meals',
              url: 'https://example.com/tip2',
              lang: 'en',
              agree_count: 15,
              disagree_count: 1,
            },
          },
        },
      ],
      location: {
        address: '124 Main St',
        formatted_address: '124 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.7135,
          longitude: -74.0058,
        },
      },
      distance: 250,
      rating: 4.2,
      tel: '555-555-5552',
      website: 'https://testplace2.example.com',
    },
    {
      fsq_id: '1234-3',
      name: 'Test Place 3',
      categories: [
        {
          id: 1,
          name: 'Café',
          short_name: 'Cafe',
          plural_name: 'Cafés',
          icon: {
            id: 'icon123-3',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-3',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Cozy atmosphere',
              url: 'https://example.com/tip3',
              lang: 'en',
              agree_count: 8,
              disagree_count: 0,
            },
          },
        },
      ],
      location: {
        address: '125 Main St',
        formatted_address: '125 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.712,
          longitude: -74.0072,
        },
      },
      distance: 350,
      rating: 4.7,
      tel: '555-555-5553',
      website: 'https://testplace3.example.com',
    },
    {
      fsq_id: '1234-4',
      name: 'Test Place 4',
      categories: [
        {
          id: 2,
          name: 'Restaurant',
          short_name: 'Rest',
          plural_name: 'Restaurants',
          icon: {
            id: 'icon123-4',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-4',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Elegant dining',
              url: 'https://example.com/tip4',
              lang: 'en',
              agree_count: 20,
              disagree_count: 3,
            },
          },
        },
      ],
      location: {
        address: '126 Main St',
        formatted_address: '126 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.7142,
          longitude: -74.008,
        },
      },
      distance: 500,
      rating: 4.0,
      tel: '555-555-5554',
      website: 'https://testplace4.example.com',
    },
    {
      fsq_id: '1234-5',
      name: 'Test Place 5',
      categories: [
        {
          id: 1,
          name: 'Café',
          short_name: 'Cafe',
          plural_name: 'Cafés',
          icon: {
            id: 'icon123-5',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-5',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Best espresso in town',
              url: 'https://example.com/tip5',
              lang: 'en',
              agree_count: 12,
              disagree_count: 2,
            },
          },
        },
      ],
      location: {
        address: '127 Main St',
        formatted_address: '127 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.711,
          longitude: -74.005,
        },
      },
      distance: 150,
      rating: 4.3,
      tel: '555-555-5555',
      website: 'https://testplace5.example.com',
    },
    {
      fsq_id: '1234-6',
      name: 'Test Place 6',
      categories: [
        {
          id: 2,
          name: 'Restaurant',
          short_name: 'Rest',
          plural_name: 'Restaurants',
          icon: {
            id: 'icon123-6',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-6',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Great for family dining',
              url: 'https://example.com/tip6',
              lang: 'en',
              agree_count: 18,
              disagree_count: 1,
            },
          },
        },
      ],
      location: {
        address: '128 Main St',
        formatted_address: '128 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.713,
          longitude: -74.0065,
        },
      },
      distance: 900,
      rating: 3.8,
      tel: '555-555-5556',
      website: 'https://testplace6.example.com',
    },
    {
      fsq_id: '1234-7',
      name: 'Test Place 7',
      categories: [
        {
          id: 1,
          name: 'Café',
          short_name: 'Cafe',
          plural_name: 'Cafés',
          icon: {
            id: 'icon123-7',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-7',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Cozy spot for coffee and pastries',
              url: 'https://example.com/tip7',
              lang: 'en',
              agree_count: 9,
              disagree_count: 0,
            },
          },
        },
      ],
      location: {
        address: '129 Main St',
        formatted_address: '129 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.7125,
          longitude: -74.0055,
        },
      },
      distance: 1200,
      rating: 4.9,
      tel: '555-555-5557',
      website: 'https://testplace7.example.com',
    },
    {
      fsq_id: '1234-8',
      name: 'Test Place 8',
      categories: [
        {
          id: 2,
          name: 'Restaurant',
          short_name: 'Rest',
          plural_name: 'Restaurants',
          icon: {
            id: 'icon123-8',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-8',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Cozy ambiance with gourmet dishes',
              url: 'https://example.com/tip8',
              lang: 'en',
              agree_count: 11,
              disagree_count: 1,
            },
          },
        },
      ],
      location: {
        address: '130 Main St',
        formatted_address: '130 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.714,
          longitude: -74.0045,
        },
      },
      distance: 850,
      rating: 4.1,
      tel: '555-555-5558',
      website: 'https://testplace8.example.com',
    },
    {
      fsq_id: '1234-9',
      name: 'Test Place 9',
      categories: [
        {
          id: 1,
          name: 'Café',
          short_name: 'Cafe',
          plural_name: 'Cafés',
          icon: {
            id: 'icon123-9',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-9',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Quiet place for a quick break',
              url: 'https://example.com/tip9',
              lang: 'en',
              agree_count: 7,
              disagree_count: 1,
            },
          },
        },
      ],
      location: {
        address: '131 Main St',
        formatted_address: '131 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.715,
          longitude: -74.007,
        },
      },
      distance: 1300,
      rating: 3.9,
      tel: '555-555-5559',
      website: 'https://testplace9.example.com',
    },
    {
      fsq_id: '1234-10',
      name: 'Test Place 10',
      categories: [
        {
          id: 2,
          name: 'Restaurant',
          short_name: 'Rest',
          plural_name: 'Restaurants',
          icon: {
            id: 'icon123-10',
            created_at: '2025-04-10T13:41:40.077Z',
            prefix: 'https://example.com/icon/',
            suffix: '.png',
            width: 64,
            height: 64,
            classifications: ['food'],
            tip: {
              id: 'tip123-10',
              created_at: '2025-04-10T13:41:40.077Z',
              text: 'Vibrant place with live music',
              url: 'https://example.com/tip10',
              lang: 'en',
              agree_count: 14,
              disagree_count: 2,
            },
          },
        },
      ],
      location: {
        address: '132 Main St',
        formatted_address: '132 Main St, Anytown, USA',
      },
      geocodes: {
        main: {
          latitude: 40.7105,
          longitude: -74.0067,
        },
      },
      distance: 750,
      rating: 4.6,
      tel: '555-555-5560',
      website: 'https://testplace10.example.com',
    },
  ],
  context: {
    geo_bounds: {
      circle: {
        center: {
          latitude: 40.7128,
          longitude: -74.006,
        },
        radius: 500,
      },
    },
  },
};
